- name: fail for unsupported os
  fail:
    msg: This playbook runs only on ubuntu
  when: ansible_os_family != 'RedHat'
- name: install packages for ubuntu
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_centos }}"
  tags:
    - nagios
