---
# handlers file for testrole
- name: enable and restart apache2
  service:
    name: apache2
    enabled: true
    state: restarted
  tags:
    - plugin
- name: enable and restart nagios
  service:
    name: nagios
    enabled: true
    state: restarted
  tags:
    - plugin

